---
title: "Setup"
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Setup}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}  
---

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
library(aquap2)
```

[Back to introduction](introduction.html)

To increase readability and ease of use, all the options for package `aquap2` are available in the `settings.r` file. This is an ordinary .r file that gets copied from the package to a folder of your choice, and it is used to set the defaults for many arguments and to control the general behaviour of the package.

An advantage of having the settings.r file in a user-defined location *outside* the package is that personal modifications do *not* get lost when the package itself is being updated. Should a newer version of the settings.r file be available after an update, you will get notified and the additinal elements will be listed. Depending on the amount of changes you made to the settings.r file, you can now either just replace the old settings.r file with the new one, or copy the new elements into the 'old' file where you already made all your changes.

## The .Renviron file
All you have to do to setup `aquap2` is to define the path to a folder of your choice in the variable `AQUAP2SH` in your `.Renviron` file. If you do *not* have a .Renviron file in your **home directory** you have to create one.

In the .Renviron file, simply add the line: 
```
AQUAP2SH = /Users/bernhard/Documents/.../.../myFolder
```
with a valid path to the folder where the setting.r file then will live. (In this example called `myFolder`.)


You can check if the setup is completed by calling
```
updateSettings()
#> aquap2 settings updated
```
If you get the message printed above, everything is ready.
